### ISSUE TITLE
remove right panel in the report tab

### ISSUE THREAD

**Issue by lkuiucsb** [IMCR-Hackathon/datapie#77]
The report figures were constrained by the existence of right panel. Need to remove

**Comment by clnsmth** [comment]
Just looked at the code. The report doesn't have a right panel but seems to be constrained by the main (center) panel, which has consistent dimension throughout all UI tabs. Solution might be to create a conditional statement within the `mainPanl()` (~line 163) for the report dimensions.

**Comment by sheilasaia** [comment]
@clnsmth, i can work on this. i'm thinking we probably only need the right panel for the plot and interactive plot tabs. does that sound ok?

**Comment by lkuiucsb** [comment]
@sheilasaia Yes, that was what we discuss: keeping the right panel for the plot and interactive plot tabs only.  I haven't had time looking into it. If you want to give it a try, please go ahead.

**Comment by sheilasaia** [comment]
After looking into this, I made the main panel a little wider and the right panel a little narrower but think it's going to be tough for us to completely remove the right panel from the non-plot-related tabs without really changing how the shiny app UI code is written (i.e., using `fluidPage(fluidRow(column(...)))` rather than the current `fluidPage(sidebarPanel(width = X,...))`. There might be a third way but I am worried it won't scale well for different monitor sizes. I was able to constrain the data table so it doesn't look like the exception; it now fits the same dimensions as the rest of the main panel tabs and the user can scroll left and right to see the rest of the variables. Would be happy to discuss this more with you all at our next meeting, @lkuiucsb @clnsmth @atn38!

**Comment by clnsmth** [comment]
@sheilasaia, could you revert the `development` branch back to the state before you merged this work, and keep the work in a separate branch for folks to review and discuss?

**Comment by sheilasaia** [comment]
@clnsmth, sure! sorry about that!

**Comment by sheilasaia** [comment]
I hope that worked....

**Comment by sheilasaia** [comment]
@clnsmth if you could give me any specifics about how it was showing up on your computer that would be helpful.

**Comment by atn38** [comment]
Taking a stab at this via branch fix_77. 

I'm gonna try two approaches: 
- a rather significant change: using `navbarPage()` instead of `fluidPage()` as the top-level layout grid. See [this Shiny grid layout guide](http://shiny.rstudio.com/articles/layout-guide.html) for the difference.
- wrapping the sidebarPanel inside the mainPanel. Right now they are level with each other.

**Comment by clnsmth** [comment]
At fix77b, I'll try full screen width report/plot/interactive-plot tabs and move the controls to the top or bottom of the report/plot area.

**Comment by clnsmth** [comment]
A prototype of the "full screen width" version is now available at fix_77b.

**Comment by clnsmth** [comment]
Hey folks we have 2 options for fixing this issue and would like to know which you prefer:

1.) Remove only the right panel (currently empty space) of report tab to extend the report width by the width of the right panel (branch "fix_77").
2.) Move the left and right panels to the top so the report and plot areas are maximized to the full width of the screen (branch fix_77b).

If you'd like to test out in your R Studio environment:

* Open the R Studio "datapie.Rproj"
* Open the terminal (Tools > Terminal > Move focus to terminal)
* At the terminal enter "git pull origin branchname"
* At the terminal enter "git checkout branchname"
* In the Console enter "devtools::load_all(".")"
* In the Console enter "datapie_shiny()"

_NOTE: Please ignore the "Interactive Plot" tab for now and focus on the layout._

**Comment by clnsmth** [comment]
Preview of Option 2:
![option_2](https://user-images.githubusercontent.com/25492069/67058215-b201b700-f108-11e9-8339-cef898587cbe.gif)

**Comment by vanderbi** [comment]
I really like this layout!

**Comment by ktoddbrown** [comment]
I also really like the stacked layout instead of the side-to-side.

**Comment by clnsmth** [comment]
Alright folks, we're going with the larger plot/report option (branch fix_77b), but should try to incorporate a smaller rendering of the plot when setting parameters so the user can see how it changes (i.e. @jhp7e's suggestion for collapsible controls).

**Comment by clnsmth** [comment]
branch fix_77b has been merged into the development branch.

Additional features that were implemented:
- **Removal of the static plot  tab** Maintaining both static and interactive plot tabs is superfluous, especially in light of the substantial performance gains provided by adopting the plotly library.
- **Adoption of the plotly library** Adopting this library as the sole plotting library for the "Plot" tab dramatically reduces processing time and provides many exciting interactive plotting features that cannot be met by ggplot2 or by wrapping ggplot2 objects with `plotly::ggplotly()`. Albeit, some cool ggplot2 features were lost but this was for the sake of improved performance.
- **Reduced plotting controls** Many of the plotting controls were obsoleted by the new interactive plotting features and therefore removed. Many plotting controls were removed due to a lack of support within plotly or because of the large effort required to support these amenities in a plotly only interface. Note, loss of these controls doesn't compromise the project's scope.
- **Updated Help tab** Required by the changes
- **Increased limit of file uploads** Local file upload size was increased to 5 GB.
- **Reformatted and annotated `datapie_shiny()`** Formatting and comments were a mess. Now at least they are a consistent mess  : )
